include ../../../build/Makefile.dirs
include ${BUILDDIR}/Makefile.conf

MY_LIB = ${LIBDIR}/libMsise.a

OBJECTS = \
	hwm14.o\
	utils_constants.o\
	physics_constants.o\
	utils_spline.o\
	physics_msis.o

# These may not even be compiled???
# hwm93.f90
# nrlmsise00_driver.for
# nrlmsise00_sub.for
# test77gtd7.f
# testgtd7.f90

LIB:
	@echo '--> Compiling MSIS in ${MSISDIR} <--'
	@make --no-print-directory -f Makefile.UM ${MY_LIB}

${MY_LIB}: ${MF} ${MODULES} ${OBJECTS}
	@echo '--> Creating MSIS library <--'
	@rm -f ${MY_LIB}
	${AR} ${MY_LIB} ${MODULES} ${OBJECTS}
